pipeline{
  agent any
  
  
  environment { 
      CI = 'true'
  }
  stages{
    stage ("Build"){
      steps {
        echo "Building the app..."
        dir ("/var/lib/jenkins/workspace/SpectacularKaraoke/API"){
          sh "npm install --no-optional"
        }

      }
        
    }
    stage ("Test"){
      steps{
        echo "Testing the app"
        dir ("/var/lib/jenkins/workspace/SpectacularKaraoke/API"){
          sh "npm install chai --no-optional"
          sh "npm install mocha --no-optional"
          sh "npm test"
        }
        
      }
      
    }
    stage ("Analyze"){
      steps{
        echo "Analyzing the app"
      }
      
    }
    stage ("Deploy"){
      steps{
        echo "Deploying the app"
      }
        
    }
  }
  
}
