pipeline{
  agent any
  
    stages{
      stage ("Build"){
        steps {
          rm "-rf *.tar.gz"
          npm "install"
          tar "czf SpectacularKaraoke-$BUILD_NUMBER.tar.gz node_modules API Diagrams"
        }
        
      }
      
    }
  
}
