pipeline{
  agent any
  
    stages{
      stage ("Build"){
        steps {
          sh "cd /API"
          sh "rm -rf *.tar.gz"
          sh "npm install"
          sh "tar czf SpectacularKaraoke-$BUILD_NUMBER.tar.gz node_modules API Diagrams"
        }
        
      }
      
    }
  
}
